apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false

  - name: Maintenance PostgreSQL
    uid: maintenance-postgres
    type: postgres
    access: proxy
    url: db:5432
    user: $POSTGRES_USER
    database: $POSTGRES_DB
    isDefault: false
    editable: false
    jsonData:
      postgresVersion: 1600
      sslmode: disable
      timescaledb: false
    secureJsonData:
      password: $POSTGRES_PASSWORD
